chaty/urls.py
from django.urls import path, include

from . import admin
from .views import base_views, chatroom_views

app_name = 'chaty'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('chatroom_list/', chatroom_views.chatroom_list, name='chatroom_list'),
    path('chatroom/create', chatroom_views.chatroom_create, name='chatroom_create'),
    path('chatroom/join', chatroom_views.chatroom_join, name='chatroom_join'),
    path('chatroom/<int:chatroom_id>', chatroom_views.chatroom_chat, name='chatroom_chat'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from chaty.views import base_views

app_name = 'chaty'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaty/', include('chaty.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index')
]

chaty/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Chatroom(models.Model):
    roomname = models.CharField(max_length=50, unique=True)
    latest_message = models.ForeignKey("Message", on_delete=models.CASCADE, null=True, default=None)
    creationtime = models.DateTimeField(auto_now_add=True)

class Chat(models.Model):
    participant = models.ForeignKey(User, on_delete=models.CASCADE)
    chatroom = models.ForeignKey("Chatroom", on_delete=models.CASCADE)

    class Meta:
        unique_together = ('participant', 'chatroom')

class Message(models.Model):
    chat = models.ForeignKey("Chat", on_delete=models.CASCADE, default=None)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    message = models.TextField()
    senttime = models.DateTimeField(auto_now_add=True)
    viewedcnt = models.IntegerField(default=0)

common/models.py
from django.db import models

# Create your models here.

chaty/forms.py
from django import forms
from chaty.models import Chatroom
from chaty.models import Message

class ChatroomForm(forms.ModelForm):
    class Meta:
        model = Chatroom
        fields = ['roomname']
        labels = {
            'roomname': 'roomname',
        }

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {
            'message': 'message',
        }

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserFrom(UserCreationForm):
    email = forms.EmailField(label="email")

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

chaty/views/base_views.py
from django.shortcuts import render
from ..models import Chatroom
from django.core.paginator import Paginator
from django.db.models import Q

def index(request):
    return render(request, 'chaty/landing.html')


def chatroom_list(request):
    chatroom_list = Chatroom.objects.order_by('-creationtime')
    page = request.GET.get('page', '1')
    if chatroom_list:
        chatroom_list = chatroom_list.filter(
            Q(chat__participant=request.user)
        ).distinct()
    paginator = Paginator(chatroom_list, 10)
    page_obj = paginator.get_page(page)
    context = {'chatroom_list': page_obj}

    return render(request, 'chaty/chatroom_list.html', context)

chaty/views/chatroom_views.py
from django.contrib import messages

from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q


from ..forms import ChatroomForm, MessageForm
from ..models import Chatroom
from ..models import Chat
from ..models import Message

@login_required(login_url='common:login')
def chatroom_list(request):
    chatroom_list = Chatroom.objects.order_by('-creationtime')
    page = request.GET.get('page', '1')
    if chatroom_list:
        chatroom_list = chatroom_list.filter(
            Q(chat__participant=request.user)
        ).distinct()
    paginator = Paginator(chatroom_list, 10)
    page_obj = paginator.get_page(page)
    context = {'chatroom_list': page_obj}

    return render(request, 'chaty/chatroom_list.html', context)

@login_required(login_url='common:login')
def chatroom_create(request):
    #create chatroom
    if request.method == 'POST':
        form = ChatroomForm(request.POST)
        if form.is_valid():
            chatroom = form.save(commit=False)
            chatroom.creationtime = timezone.now()
            chatroom.save()

            chat = Chat()
            chat.chatroom = chatroom
            chat.participant = request.user
            chat.save()
            return redirect('chaty:index')
    #show chatroom
    else:
        form = ChatroomForm()
    context = {'form': form}
    return render(request, 'chaty/chatroom_create_form.html', context)


@login_required(login_url='common:login')
def chatroom_join(request):
    if request.method == 'POST':
        roomname = request.POST['roomname']
        chatroom = Chatroom.objects.filter(roomname=roomname)
        if not chatroom.exists():
            messages.error(request, 'Room does not exist')
            return render(request, 'chaty/chatroom_join_form.html')
        else:
            ###수정중
            chat_db = Chat.objects.get(chatroom=chatroom.get())
            print(chat_db)
            if chat_db:
                return redirect('chaty:chatroom_chat', chatroom_id=chatroom.get().id)

            chat = Chat()
            chat.chatroom = chatroom.get()
            chat.participant = request.user
            chat.save()
            return redirect('chaty:chatroom_chat', chatroom_id=chatroom.get().id)
    else:
        return render(request, 'chaty/chatroom_join_form.html')

@login_required(login_url='common:login')
def chatroom_chat(request, chatroom_id):
    #create msg
    if request.method == 'POST':
        # ajax는 나중에 해보장
        form = MessageForm(request.POST)
        if form.is_valid():
            msg = form.save(commit=False)
            msg.sender = request.user
            msg.message = form.cleaned_data['message']
            msg.sent_time = timezone.now()
            msg.viewedcnt = 1
            msg.chat = Chat.objects.get(pk=chatroom_id)
            msg.save()
            chatroom = Chatroom.objects.get(pk=chatroom_id)
            chatroom.latest_message = msg
            chatroom.save()
            return redirect('{}#msg_{}'.format(resolve_url('chaty:chatroom_chat', chatroom_id=chatroom_id), msg.id))
            #return redirect('chaty:chatroom_chat', chatroom_id=chatroom_id)
    #show msgs
    else:
        chatroom = get_object_or_404(Chatroom, pk=chatroom_id)
        participant_dict_list = list(Chat.objects.filter(chatroom_id=chatroom_id).values('participant_id'))
        participant_list = list()
        for dict in participant_dict_list:
            participant_list.append(dict['participant_id'])
        if request.user.id not in participant_list:
            return redirect('chaty:index')

        message_list = Message.objects.filter(chat__chatroom=chatroom)
        context = {"chatroom": chatroom, 'message_list': message_list, 'participant_cnt': len(participant_list)}
        return render(request, 'chaty/chatroom.html', context)

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from common.forms import UserFrom

# Create your views here.


def logout_view(request):
    logout(request)
    return redirect('index')

def signup(request):
    if request.method == 'POST':
        form = UserFrom(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('index')
    else:
        form = UserFrom()
    return render(request, 'common/signup.html', {'form': form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Chaty~~</title>
</head>
<body>
    {% include "navbar.html" %}
{% block content %}
{% endblock %}
<script src="{% static 'bootstrap.bundle.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/chaty/chatroom.html
{% extends 'base.html' %}
{% load chaty_filter %}
{% block content %}
<h3 class="border-bottom py-2">채팅방 이름: {{ chatroom.roomname }}</h3>
<h6 class="border-bottom py-2">채팅방 ID: {{ chatroom.id }}</h6>
<div class="container">
    <div class="row ">
        <div class="col">
        {% if message_list %}
            {% for msg in message_list %}
                <div class="card mb-2" id="msg_{{ msg.id }}">
                    <div class="card-header">
                        {{ msg.sender }} // {{ msg.senttime }}
                        <span class="badge text-bg-secondary">{{ participant_cnt|sub:msg.viewedcnt }}</span>
                    </div>
                    <div class="card-body{% if msg.sender == request.user %} bg-primary-subtle {% endif %}">
                        {{ msg.message }}
                    </div>
                </div>
            {% endfor %}
            <div class="mb-5">

            </div>
        {% endif %}
        </div>
        <div style="height: 10rem"></div>
    </div>
    <div class="row fixed-bottom">
        <form method="post">
            {% csrf_token %}
                <div class="row mb-4">
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <div class="mb-3">
                              <label for="message" class="form-label">Example input</label>
                              <input class="form-control" name="message" id="message">
                            </div>
                            <button type="submit" class="btn btn-primary">전송</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
    setTimeout(() => {
        window.scrollTo(0, document.body.scrollHeight);
    }, 0);
</script>
{% endblock %}

templates/chaty/chatroom_create_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3">
    <form method="post" action="{% url 'chaty:chatroom_create' %}">
        {% csrf_token %}
        <input type="hidden" name="text" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="roomname">생성할 roomname</label>
            <input type="text" class="form-control" name="roomname" value="{{ form.roomname.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성</button>
    </form>
    </div>
{% endblock %}

templates/chaty/chatroom_join_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3">
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
                <strong>{{ message.tags }}</strong>
                <ul><li>{{ message.message }}</li>
                </ul>
            {% endfor %}
        </div>
    {% endif %}
    <form method="post" action="{% url 'chaty:chatroom_join' %}">
        {% csrf_token %}
        <input type="hidden" name="text" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="roomname">입장할 roomname</label>
            <input type="text" class="form-control" name="roomname" id="roomname" value="{{ form.roomname.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">입장</button>
    </form>
    </div>
{% endblock %}

templates/chaty/chatroom_list.html
{% extends 'base.html' %}
{% load chaty_filter %}
{% block content %}
    {% if not user.is_authenticated %}
        <div class="container my-3">
            <div class="card nt-3">
                <div class="card-header">로그인을 하라구요~</div>
                <div class="card-body">
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                </div>
            </div>
        </div>
    {% else %}
    <div class="container my-3">
        <a href="{% url 'chaty:chatroom_create' %}" class="btn btn-primary">채팅방 만들기</a>
        <a href="{% url 'chaty:chatroom_join' %}" class="btn btn-primary">채팅방 들어가기</a>
    </div>
    <table class="table">
        <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th>채팅방 이름</th>
                <th>최근 메시지</th>
            </tr>
        </thead>
        <tbody>
        {% if chatroom_list %}
            {% for chatroom in chatroom_list %}
                <tr class="text-center">
                    <td>
                        {{ chatroom_list.paginator.count|sub:chatroom_list.start_index|sub:forloop.counter0|add:1 }}
                    </td>
                    <td class="text-start">
                        <a href="{% url 'chaty:chatroom_chat' chatroom.id %}">{{ chatroom.roomname }}</a>
                    </td>
                    <td>{{ chatroom.latest_message.message }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
            <td colspan="3">채팅방이 없네요ㅠ</td>
            </tr>
        {% endif %}
        </tbody>
    </table>
    <ul class="pagination justify-content-center">
    {% if chatroom_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ chatroom_list.previous_page_number }}" href="javascript:void(0)">이전</a>
        </li>
    {% else %}
        <li class="page-item">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
    {% endif %}
    {% for page_number in chatroom_list.paginator.page_range %}
        {% if page_number >= chatroom_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == chatroom_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)"{{ page_number }}></a>
            </li>
        {% else %}
            <li class="page-item" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)"{{ page_number }}></a>
            </li>
        {% endif %}
        {% endif %}
    {% endfor %}
    {% if question_list.has_next %}
        <li class="page-item">
        <a class="page-link" data-page="{{ question_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
    {% else %}
        <li class="page-item">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
    {% endif %}
    </ul>

    {% endif %}
{% endblock %}

{% block script %}
<script type="text/javascript">

</script>
{% endblock %}

templates/chaty/landing.html
{% extends 'base.html' %}
{% block content %}


<div class="my-3 d-grid gap-2 col-6 mx-auto ">
    <a href="{% url 'chaty:chatroom_list' %}" class="btn btn-primary btn-lg">채팅 시작~~</a>
</div>

{% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="text" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ from.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label type="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
    </div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
    <div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
    </div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    <div class="alert alert-danger">
        {% for field in form %}
            <div>
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            </div>
        {% endfor %}
        {% for error in form.non_field.errors %}
            <div>
            <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'chaty:index' %}">Chaty</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} [로그아웃]</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">[로그인]</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:signup' %}">[회원가입]</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>